### PR TITLE
Various cleanups and fixes in Virtaal tutorial

### LINKED ISSUE #3235: Double words in english strings
I noticed some mistakes in the english text while translating:

"to to":

> 	An accelerator key is a key on your keyboard that you can press to to quickly

"to to":

> 	This message contains a large number that is formatted according to to American

"on on":

> 	This message contains a link that the user will be able to click on on to

### PR DESCRIPTION
**Pull request by unho**
Fixes #3235

### CODE REVIEW

**Comment by friedelwolff** [comment]
Thanks, Leandro. Please commit. I'll still try to review everything. The tutorial looks a bit big now, so I'm thinking of also reviewing it for size, etc.

@dwaynebailey If you want to review this commit (or rather the whole tutorial) from a native speaker's perspective, feel free to do so (keeping in mind that most readers won't be native speakers ;-)

**Comment by unho** [comment]
I am committing.

Regarding its size, I still think that there might be some features that are still not covered, so perhaps it is still not big enough.

**Comment by friedelwolff** [comment]
Well, then we need to talk about goals. It was not my goal to cover everything, but it seems like what you want to achieve. At the moment it adds about 2000 words to the UI translation (more than double what it was before). So maybe we can at least review the instructions for brevity (to reduce the 2000 words).

I also want to make it easy for people to localise Virtaal easily, and it is now quite a bit of work to do (compared to before). That doesn't mean we shouldn't do it, just that we should consider it. Regardless, thanks for the work on this.

**Comment by unho** [comment]
Ideally Virtaal localization should consists on two POT files: one for UI and other for the tutorial. This way it is easier for translators to focus their efforts into UI which is far more important.

Regardless of that looking for brevity looks like a good idea as longs as we don't loose the goal of covering the basics of the important features users should know, and that instructions are still understandable. Perhaps you are better suited for carry on with this task, but I will be happy to review and provide input on this.

**Comment by unho** [comment]
@friedelwolff For example some improvements for tutorial have been suggested in https://sourceforge.net/p/translate/mailman/message/34908678/

**Pull request merged**
