### PR TITLE
Update travis-ci config for Python 3

### PR DESCRIPTION
**Pull request by llimeht**
Enable building in travis-ci with Python 3.7

The test suite is not yet run and perhaps does not yet pass anyway. We can add a pytest call to the end when appropriate.

### CODE REVIEW

**Comment by friedelwolff** [comment]
Thank you for your contribution.

For now I'm planning on supporting at least Python 3.6. Can we maybe add that?

Also, can you put in your compileall script you used to find incompatible code? Is it feasible to still keep 2.7 alive for a while? (I think it is all still compatible or trivial to make it if we already regressed.)

If you have any ideas of how to get more automated tests running, I'd be very happy - we are constantly paying for the lack of tests.

**Comment by llimeht** [comment]
Sure, I'll have a look at those extra bits and see what I can do.

In general, it's much easier to write code that is Python 3-only than it is polyglot code to handle both versions. I'm also not sure that there's a market for a virtaal that needs a relatively recent PyGObject/Gtk3 but is running on an old interpreter. I'd be all in favour of stopping any attempt to support Python 2.7 so that the code is simpler.

**Comment by llimeht** [comment]
I've updated this PR to test against Python 3.6, 3.7 and 3.8. The tests fail against 2.7 with lots of GObject errors. 

Note that this PR is now built on top of #3308 so that the tests actually pass, but that does mean that it looks like there are far more commits in the sequence. I can rebase it back to the `py3` branch once #3308 is merged if you'd like a simpler history.

**Comment by friedelwolff** [comment]
Many thanks for the work on this!

**Pull request merged**
