### PR TITLE
Update danish (da) translation to 100% translated

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by unho** [comment]
Would be great if you could upload it to http://pootle.locamotion.org/da/virtaal/ as well.

**Comment by scootergrisen** [comment]
Ok it seems there are missing instructions as how to submit translations or maybe i have missed it?

**Comment by scootergrisen** [comment]
Does my suggestions have to be approved by other people on Pootle before the strings get into the release?

**Comment by unho** [comment]
> Does my suggestions have to be approved by other people on Pootle before the strings get into the release?

Probably not. I was suggesting to upload the translations to Pootle so Virtaal translation for Danish is displayed as complete (or more complete) and prevent other Danish translators from translating again what you already translated.

**Comment by friedelwolff** [comment]
Thank you for looking into this. Please note that we are not yet in the string freeze period (although it could be within a few days if I manage to finish my last review of strings).

In cases where an existing translation exists, we will obviously ask you to liaise with the existing translator so that there is opportunity for review and discussion. That way, hopefully the end result is even better!

Thanks again.

**Pull request closed without merging**
