### PR TITLE
Misc Python 3 porting fixups

### PR DESCRIPTION
**Pull request by llimeht**
A few additional things to fix found either when running the program or running py3compile over all files as part of updating the Debian packaging.

### CODE REVIEW

**Comment by llimeht** [comment]
@friedelwolff I guess merge conflicts here were entirely predictable. Do you want me to rebase or will you just cherry-pick the bits that are useful?

**Comment by friedelwolff** [comment]
Sorry about that. I had a lot of changes queued, and we didn't see each other's work. I'll try to go through this, but my time is now less from today on. I'll try to see if you had some better solutions.

Thank you for the contribution.

**Comment by llimeht** [comment]
No worries @friedelwolff! I think we had either the same solution or you had a better solution to several of them. I'll try to rebase the branch to make it easy to see what else I had found.

**Comment by rffontenelle** [comment]
@llimeht by running `grep -R ' u"'` in the root directory of your temporary branch, I notice occurrence of strings being set as Unicode. AFAIK is needed for Python 2 only. Can you please check if these `u` can be removed too?

**Comment by rffontenelle** [comment]
Same applies to `grep -R " u'"`

**Comment by rffontenelle** [comment]
`2to3` seems to be very handy on the migration.

**Comment by llimeht** [comment]
There are other `u"…"` constructs in the code base that are cruft and can be fixed some time in the future. There is no rush. They are a no-op from Python 3.3 onwards (see PEP 414).

There is only one `ur"…"` in the code base; `ur"…"` is a syntax error and so needs fixing not merely decrufting.

```
$ python2.7
>>> punc_symbols = ur'''.,?!:;'"“”‘’—)'''
>>> 
```

```
$ python3.7
>>> punc_symbols = ur'''.,?!:;'"“”‘’—)'''
  File "<stdin>", line 1
    punc_symbols = ur'''.,?!:;'"“”‘’—)'''
                                        ^
SyntaxError: invalid syntax
```

BTW if you intend to actively find and remove them, then your grep will miss the very many instances of `(u"…")`.

**Comment by friedelwolff** [comment]
Thank you for the work on this. Just a general comment:

The difference from the master branch is huge, so let's restrict the changes to what is required for now. The u'' strings don't do any harm, so let's keep them for now just to make reviews easier in the next while.

I'll try to have a look at this later. Thank you for the help and reviews so far!

**Pull request merged**
